### ISSUE TITLE
PHP8?

### ISSUE THREAD

**Issue by broksonic21** [umutphp/php-docker-images-for-ci#12]
**Describe the solution you'd like**
Do you have PHP8 images?

**Comment by umutphp** [comment]
Hi @broksonic21 ,

I am waiting for the official docker image for PHP8. Currently, DockerHub has only RC images.

**Comment by umutphp** [comment]
Hi @broksonic21 ,

The image for PHP 8.0 is ready. Many thanks for the issue :). I am closing it now.

[https://hub.docker.com/repository/docker/umutphp/php-docker-images-for-ci](https://hub.docker.com/repository/docker/umutphp/php-docker-images-for-ci)
