### ISSUE TITLE
PHPInsights not in php 8.0 image?

### ISSUE THREAD

**Issue by broksonic21** [umutphp/php-docker-images-for-ci#15]
**Describe the bug**
Doesn't seem to be able to find the phpinsights on php8.0 image

(BTW: I realize these might not be ready, I was just trying them, so sending reports over as I see them. Feel free to punt if not a priority!)

**Describe How To Reproduce**

```
~/git/wprepo:master ✓ ➭docker run -v $(pwd)/src:/app umutphp/php-docker-images-for-ci:8.0 phpinsights
docker: Error response from daemon: OCI runtime create failed: container_linux.go:370: starting container process caused: exec: "phpinsights": executable file not found in $PATH: unknown.
ERRO[0001] error waiting for container: context canceled
```

**Comment by umutphp** [comment]
Hi @broksonic21 ,

I think the package is not ready for PHP 8.0.

**Comment by broksonic21** [comment]
I'm no longer actively needing this, so closing this out as it's 4+ years old and has been addressed since this was filed
