### ISSUE TITLE
2 different versions of var-dump-check in 8.3 image

### ISSUE THREAD

**Issue by chasebolt** [umutphp/php-docker-images-for-ci#30]
**Describe the bug**
Currently there are 2 different versions of `var-dump-check` in the `8.3` image. Both have different md5 and behave differently. The version located at `/tools/php-parallel-lint/php-var-dump-check/vendor/php-parallel-lint/php-var-dump-check/var-dump-check` appears to be the most recent.
```
b1a58a05c3dbfcffe89bf4e8a5fee71a  /tools/php-parallel-lint/php-var-dump-check/vendor/php-parallel-lint/php-var-dump-check/var-dump-check
483a89186ce74f90601abb7623f8826b  /usr/local/bin/var-dump-check
```
**Describe How To Reproduce**
```bash
docker run -it --rm umutphp/php-docker-images-for-ci:8.3 bash
md5sum /tools/php-parallel-lint/php-var-dump-check/vendor/php-parallel-lint/php-var-dump-check/var-dump-check /usr/local/bin/var-dump-check
```

**Comment by umutphp** [comment]
@chasebolt Many thanks for the bug. Let me check and update you.

**Comment by umutphp** [comment]
@chasebolt The `composer` command is [configured](https://github.com/umutphp/php-docker-images-for-ci/blob/1f284d545afe342a5698fa60486aa905c4ba74fa/images/8.3/Dockerfile#L42C1-L44C76) to install all the commands under the `/user/local/bin` folder. So, the one under the `/user/local/bin` folder is correct. I am not sure about the other executable.

**Comment by chasebolt** [comment]
Strange ok thanks. I'll close this out then.
