### ISSUE TITLE
Unset COMPOSER_BIN_DIR Variable

### ISSUE THREAD

**Issue by umutphp** [umutphp/php-docker-images-for-ci#5]
In composer files, the **COMPOSER_BIN_DIR** is set to **/usr/local/bin** in Dockerfile as below to get the commands in global scope.

`ENV COMPOSER_BIN_DIR="/usr/local/bin"`

We need to unset the variable just after the end of composer package installations in Dockerfile.

**Comment by ig-onoffice-de** [comment]
This caused me an error. It should be reset to vendor/bin not to an empty string. Reset it on my own before running composer install and now it works for me.
You could probably also unset the variable.

**Comment by umutphp** [comment]
Hi @ig-onoffice-de ,

Many thanks for the comment :).

Let me check your solution and update you.

**Comment by umutphp** [comment]
Hi @ig-onoffice-de ,

Fixed accordingly. Many thanks for the feedback.

**Comment by exussum12** [comment]
FYI this caused an issue for us, its most likely unique to the way our code was set up. 

For future people with maybe the same issue, check the versions when you call phpmnd and the version in the composer.lock / composer.json
